version: "3.4"
services:
  animal-name-service:
    build:
      context: "./animal-name-service"
    image: com.example/animal-name-service:lastest
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=animal-name-service
  scientist-name-service:
    build:
      context: "./scientist-name-service"
    image: com.example/scientist-name-service:lastest
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=scientist-name-service
  name-generator-service:
    build:
      context: "./name-generator-service"
    image: com.example/name-generator-service:lastest
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_APPLICATION_NAME=name-generator-service
    ports:
      - "8080:8080"
  jaeger:
    image: jaegertracing/all-in-one:1.17
    ports:
      - 9090:16686